# Generated by Django 5.2.7 on 2025-12-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_evento',
            field=models.DateTimeField(null=True),
        ),
    ]
