# Generated by Django 5.2.7 on 2025-12-03 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_evento_fecha_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistido', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.evento')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaAsintiendoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('eventos', models.ManyToManyField(related_name='personas', related_query_name='qpersonas', through='catalog.Asistencia', to='catalog.evento')),
            ],
        ),
        migrations.AddField(
            model_name='asistencia',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.personaasintiendoevento'),
        ),
    ]
