# Generated by Django 5.2.7 on 2025-12-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_asistencia_personaasintiendoevento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
