# Generated by Django 5.2.7 on 2025-12-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_asistencia_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaasintiendoevento',
            name='socio_codigo',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
    ]
