# Generated by Django 5.2.7 on 2025-12-03 15:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_asistencia_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonaAsintiendoEvento',
            new_name='Persona',
        ),
    ]
