# Generated by Django 5.2.7 on 2025-12-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_rename_personaasintiendoevento_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='book',
        ),
    ]
