# Generated by Django 5.2.7 on 2025-12-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField()),
                ('prioridad', models.IntegerField()),
                ('fecha_limite', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En Revisión'), ('publicado', 'Publicado')], default='borrador', max_length=20)),
                ('es_urgente', models.BooleanField(default=False)),
            ],
        ),
    ]
